version: '{build}'
skip_commits:
  files:
  - doc/*
  - README.md
  - .vsts-ci.yml
  - .travis.yml

nuget:
  disable_publish_on_pr: true

image: Visual Studio 2017
configuration: Release

environment:
  VisualStudioVersion: 15.0

before_build:
- dotnet --info
- msbuild src\StreamRpc.sln /nologo /m /v:quiet /t:restore

build_script:
- msbuild src\StreamRpc.sln /nologo /m /fl /v:minimal /t:build,pack
- ps: |
    $version = ([xml](Get-Content obj\StreamRpc\Release\*.nuspec)).package.metadata.version
    Update-AppveyorBuild -Version $version

test_script:
- cmd: >-
    dotnet test .\src\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj --no-build --filter "TestCategory!=FailsInCloudTest"

artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: vF+hR2m3uTTUhrvJ2ER8Oox8SkWTZ4i56TY01k1NKfy5LWXEuAzmw5hlNcNSODTR
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /^(?!.*(\.Json)).*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
